=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/dtd/xdrs.dtd
<!-- begin parameter entities -->
<!ENTITY % drsexp "(var|app|drs|smerge|merge|alfa|sdrs)">
<!-- end parameter entities -->

<!-- drs -->
<!ELEMENT xdrs-output (xdrs*)>
<!ATTLIST xdrs-output  
          version CDATA #REQUIRED >

<!ELEMENT xdrs (taggedtokens,(sdrs|app|drs|smerge|merge|alfa))>
<!ATTLIST xdrs
          xml:id ID #IMPLIED >

<!ELEMENT sdrs (constituents,relations)>

<!ELEMENT constituents ((sub|constituent)+)> <!-- (sub|constituent+)> -->

<!ELEMENT sub (constituent,(sdrs|constituent))> <!-- was (constituent+)> -->

<!ELEMENT constituent (tokens?, (drs|sub))> <!-- was (tokens?, drs) -->
<!ATTLIST constituent 
          label CDATA #REQUIRED>

<!ELEMENT relations (drel*)>

<!ELEMENT drel EMPTY>
<!ATTLIST drel 
          arg1 CDATA #REQUIRED 
          arg2 CDATA #REQUIRED 
          sym CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED >
          
<!-- begin taggedtokens -->
<!ELEMENT taggedtokens (tagtoken+)>

<!ELEMENT tagtoken (tags)>
<!ATTLIST tagtoken 
          xml:id ID #REQUIRED>

<!ELEMENT tags (tag+)>

<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag 
          type (verbnet|tok|wordnet|cat|sense|sym|lemma|sem|from|to|pos|antecedent) #REQUIRED>
<!ATTLIST tag 
          n CDATA #IMPLIED>
<!-- end taggedtokens -->             

<!ELEMENT drs (domain,conds)>
<!-- <!ATTLIST drs
          type CDATA #REQUIRED > -->
<!ATTLIST drs
          label CDATA #REQUIRED >          

<!ELEMENT tokens (token*)> <!-- to remove --> 

<!ELEMENT token (#PCDATA)>

<!ELEMENT domain (dr*)>

<!ELEMENT conds (cond*)>

<!ELEMENT cond (named|pred|rel|comp|prop|not|nec|pos|or|imp|whq|duplex)>
<!ATTLIST cond
          label CDATA #REQUIRED > 

<!--<!ELEMENT conds ((timex|named|pred|card|eq|rel|prop|not|nec|pos|or|imp|whq)*)>-->

<!ELEMENT merge (%drsexp;,%drsexp;)>

<!ELEMENT smerge (%drsexp;,%drsexp;)>

<!ELEMENT lam ((var,%drsexp;)|(var,lam)|var)>

<!ELEMENT app (lam,%drsexp;)>

<!ELEMENT alfa (%drsexp;,%drsexp;)>
<!ATTLIST alfa
          type CDATA #REQUIRED >

<!ELEMENT index (#PCDATA)>
<!ATTLIST index
          pos CDATA #REQUIRED >

<!ELEMENT var (#PCDATA)>

<!ELEMENT dr (index*)>
<!ATTLIST dr
          label CDATA #REQUIRED
          name CDATA #REQUIRED 
          from CDATA #REQUIRED 
          to CDATA #REQUIRED>

<!ELEMENT pred (index*)>
<!ATTLIST pred
          arg CDATA #REQUIRED 
          symbol CDATA #REQUIRED 
          synset CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT named (index*)>
<!ATTLIST named
          arg CDATA #REQUIRED 
          symbol CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT rel (index*)>
<!ATTLIST rel
          arg1 CDATA #REQUIRED 
          arg2 CDATA #REQUIRED 
          symbol CDATA #REQUIRED
          framenet CDATA #IMPLIED 
          sense CDATA #IMPLIED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT comp (index*)>
<!ATTLIST comp
          arg1 CDATA #REQUIRED 
          arg2 CDATA #REQUIRED 
          symbol CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>


<!ELEMENT not (index*,%drsexp;)>
<!ATTLIST not
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT pos (index*,%drsexp;)>
<!ATTLIST pos
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT nec (index*,%drsexp;)>
<!ATTLIST nec
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT or (index*,(%drsexp;,%drsexp;))>
<!ATTLIST or
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT imp (index*,(%drsexp;,%drsexp;))>
<!ATTLIST imp
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT whq (index*,(%drsexp;,%drsexp;))>

<!ELEMENT duplex (index*,(%drsexp;,%drsexp;))>
<!ATTLIST duplex
		  type CDATA #REQUIRED
		  var CDATA #REQUIRED 	
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT prop (index*,%drsexp;)>
<!ATTLIST prop
          argument CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED >

<!ELEMENT timex (index*,(date|time))>
<!ATTLIST timex
          arg CDATA #REQUIRED >

<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>

<!ELEMENT words (word+)>
<!ELEMENT word (#PCDATA)>
<!ATTLIST word
          xml:id ID #REQUIRED >

<!ELEMENT postags (postag+)>
<!ELEMENT postag (#PCDATA)>
<!ATTLIST postag
          index IDREF #REQUIRED >

<!ELEMENT netags (netag*)>
<!ELEMENT netag (#PCDATA)>
<!ATTLIST netag
          index IDREF #REQUIRED >

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/de/gold/p00/d0826/de.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- Mein Onkel hat mir dieses Buch gekauft . --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="tok">Mein</tag>
     <tag type="cat">np/(n/pp)</tag>
     <tag type="sym">speaker</tag>
     <tag type="lemma">speaker</tag>
     <tag type="from">0</tag>
     <tag type="to">4</tag>
     <tag type="sem">HAS</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Of]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">Onkel</tag>
     <tag type="cat">n/pp</tag>
     <tag type="sym">uncle</tag>
     <tag type="lemma">uncle</tag>
     <tag type="from">5</tag>
     <tag type="to">10</tag>
     <tag type="sem">ROL</tag>
     <tag type="wordnet">uncle.n.01</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">hat</tag>
     <tag type="cat">(s:dcl\np)/(s:pt\np)</tag>
     <tag type="sym">hat</tag>
     <tag type="lemma">hat</tag>
     <tag type="from">11</tag>
     <tag type="to">14</tag>
     <tag type="sem">NOW</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">mir</tag>
     <tag type="cat">np</tag>
     <tag type="sym">speaker</tag>
     <tag type="lemma">speaker</tag>
     <tag type="from">15</tag>
     <tag type="to">18</tag>
     <tag type="sem">PRO</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">dieses</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">entity</tag>
     <tag type="lemma">entity</tag>
     <tag type="from">19</tag>
     <tag type="to">25</tag>
     <tag type="sem">PRX</tag>
     <tag type="wordnet">entity.n.01</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">Buch</tag>
     <tag type="cat">n</tag>
     <tag type="sym">book</tag>
     <tag type="lemma">book</tag>
     <tag type="from">26</tag>
     <tag type="to">30</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">book.n.02</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="tok">gekauft</tag>
     <tag type="cat">((s:pt\np)\np)\np</tag>
     <tag type="sym">buy</tag>
     <tag type="lemma">buy</tag>
     <tag type="from">31</tag>
     <tag type="to">38</tag>
     <tag type="sem">EXT</tag>
     <tag type="wordnet">buy.v.01</tag>
     <tag type="verbnet" n="3">[Theme,Beneficiary,Agent]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1008">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">.</tag>
     <tag type="cat">s:dcl\s:dcl</tag>
     <tag type="sym">.</tag>
     <tag type="lemma">.</tag>
     <tag type="from">38</tag>
     <tag type="to">39</tag>
     <tag type="sem">NIL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b2">
  <domain>
   <dr label="b1" name="x1" from="0" to="4"></dr>
   <dr label="b1" name="x2" from="5" to="10"></dr>
   <dr label="b2" name="x3" from="15" to="18"></dr>
   <dr label="b3" name="x4" from="19" to="25"></dr>
   <dr label="b2" name="e1" from="31" to="38"></dr>
   <dr label="b2" name="t1" from="31" to="38"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="x2" symbol="uncle" synset="uncle.n.01" from="5" to="10"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="x2" arg2="speaker" symbol="Of" framenet="Of" from="0" to="4"></rel>
   </cond>
   <cond label="b1">
    <pred arg="x1" symbol="person" synset="person.n.01" from="5" to="10"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="x1" arg2="x2" symbol="Role" framenet="Role" from="5" to="10"></rel>
   </cond>
   <cond label="b2">
    <pred arg="x3" symbol="person" synset="person.n.01" from="15" to="18"></pred>
   </cond>
   <cond label="b2">
    <comp symbol="EQU" arg1="x3" arg2="speaker" from="15" to="18"></comp>
   </cond>
   <cond label="b3">
    <pred arg="x4" symbol="book" synset="book.n.02" from="26" to="30"></pred>
   </cond>
   <cond label="b2">
    <pred arg="t1" symbol="time" synset="time.n.08" from="31" to="38"></pred>
   </cond>
   <cond label="b2">
    <comp symbol="TPR" arg1="t1" arg2="now" from="31" to="38"></comp>
   </cond>
   <cond label="b2">
    <pred arg="e1" symbol="buy" synset="buy.v.01" from="31" to="38"></pred>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="t1" symbol="Time" framenet="Time" from="31" to="38"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x4" symbol="Theme" framenet="Commerce_buy@Goods" from="31" to="38"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x3" symbol="Beneficiary" framenet="Claim_ownership@Beneficiary" from="31" to="38"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x1" symbol="Agent" framenet="Commerce_buy@Buyer" from="31" to="38"></rel>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/en/silver/p00/d0000/en.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- A Seadoo is being ridden by a woman --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">A</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">a</tag>
     <tag type="lemma">a</tag>
     <tag type="from">0</tag>
     <tag type="to">1</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DIS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">Seadoo</tag>
     <tag type="cat">n</tag>
     <tag type="sym">seadoo</tag>
     <tag type="lemma">seadoo</tag>
     <tag type="from">2</tag>
     <tag type="to">8</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">is</tag>
     <tag type="cat">(s:dcl\np)/(s:ng\np)</tag>
     <tag type="sym">be</tag>
     <tag type="lemma">be</tag>
     <tag type="from">9</tag>
     <tag type="to">11</tag>
     <tag type="pos">VBZ</tag>
     <tag type="sem">NOW</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">being</tag>
     <tag type="cat">(s:ng\np)/(s:pss\np)</tag>
     <tag type="sym">be</tag>
     <tag type="lemma">be</tag>
     <tag type="from">12</tag>
     <tag type="to">17</tag>
     <tag type="pos">VBG</tag>
     <tag type="sem">PRG</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="tok">ridden</tag>
     <tag type="cat">s:pss\np</tag>
     <tag type="sym">ride</tag>
     <tag type="lemma">ride</tag>
     <tag type="from">18</tag>
     <tag type="to">24</tag>
     <tag type="pos">VBN</tag>
     <tag type="sem">EXT</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="tok">by</tag>
     <tag type="cat">((s:dcl\np)\(s:dcl\np))/np</tag>
     <tag type="sym">by</tag>
     <tag type="lemma">by</tag>
     <tag type="from">25</tag>
     <tag type="to">27</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Agent]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">a</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">a</tag>
     <tag type="lemma">a</tag>
     <tag type="from">28</tag>
     <tag type="to">29</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DIS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1008">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">woman</tag>
     <tag type="cat">n</tag>
     <tag type="sym">woman</tag>
     <tag type="lemma">woman</tag>
     <tag type="from">30</tag>
     <tag type="to">35</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">woman.n.01</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b1">
  <domain>
   <dr label="b1" name="x1" from="0" to="1"></dr>
   <dr label="b1" name="e1" from="18" to="24"></dr>
   <dr label="b1" name="t1" from="18" to="24"></dr>
   <dr label="b1" name="t2" from="9" to="11"></dr>
   <dr label="b1" name="x2" from="28" to="29"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="x1" symbol="seadoo" synset="seadoo.n.01" from="2" to="8"></pred>
   </cond>
   <cond label="b1">
    <pred arg="t2" symbol="time" synset="time.n.08" from="9" to="11"></pred>
   </cond>
   <cond label="b1">
    <comp symbol="EQU" arg1="t2" arg2="now" from="9" to="11"></comp>
   </cond>
   <cond label="b1">
    <pred arg="e1" symbol="ride" synset="ride.v.01" from="18" to="24"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x2" symbol="Agent" framenet="Assistance@Helper" from="25" to="27"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="t2" symbol="Time" framenet="Time" from="9" to="11"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="t1" symbol="Time" framenet="Time" from="18" to="24"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x1" symbol="Theme" framenet="Carry_goods@Goods" from="18" to="24"></rel>
   </cond>
   <cond label="b1">
    <pred arg="t1" symbol="time" synset="time.n.08" from="18" to="24"></pred>
   </cond>
   <cond label="b1">
    <comp symbol="TPR" arg1="t1" arg2="now" from="18" to="24"></comp>
   </cond>
   <cond label="b1">
    <pred arg="x2" symbol="woman" synset="woman.n.01" from="30" to="35"></pred>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/de/bronze/p01/d0716/de.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- ø Euro-Disney ist ein Vergnügungspark . --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">ø</tag>
     <tag type="cat">np/n</tag>
     <tag type="wordnet">O</tag>
     <tag type="sense">0</tag>
     <tag type="sym">ø</tag>
     <tag type="lemma">ø</tag>
     <tag type="sem">DEF</tag>
     <tag type="from">0</tag>
     <tag type="to">-1</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">Euro-Disney</tag>
     <tag type="cat">n</tag>
     <tag type="sym">euro-disney</tag>
     <tag type="lemma">euro-disney</tag>
     <tag type="from">0</tag>
     <tag type="to">11</tag>
     <tag type="sem">PER</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="tok">ist</tag>
     <tag type="cat">(s:dcl\np)/np</tag>
     <tag type="sym">be</tag>
     <tag type="lemma">be</tag>
     <tag type="from">12</tag>
     <tag type="to">15</tag>
     <tag type="sem">ENS</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="2">[Co-Theme,Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">ein</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">an</tag>
     <tag type="lemma">an</tag>
     <tag type="from">16</tag>
     <tag type="to">19</tag>
     <tag type="sem">DIS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">Vergnügungspark</tag>
     <tag type="cat">n</tag>
     <tag type="sym">vergnügungspark</tag>
     <tag type="lemma">vergnügungspark</tag>
     <tag type="from">20</tag>
     <tag type="to">35</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">.</tag>
     <tag type="cat">s:dcl\s:dcl</tag>
     <tag type="sym">.</tag>
     <tag type="lemma">.</tag>
     <tag type="from">35</tag>
     <tag type="to">36</tag>
     <tag type="sem">NIL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b2">
  <domain>
   <dr label="b1" name="x1" from="0" to="-1"></dr>
   <dr label="b2" name="x2" from="16" to="19"></dr>
   <dr label="b2" name="e1" from="12" to="15"></dr>
   <dr label="b2" name="t1" from="12" to="15"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="x1" symbol="person" synset="person.n.01" from="0" to="11"></pred>
   </cond>
   <cond label="b1">
    <named arg="x1" symbol="euro-disney" from="0" to="11"></named>
   </cond>
   <cond label="b2">
    <pred arg="t1" symbol="time" synset="time.n.08" from="12" to="15"></pred>
   </cond>
   <cond label="b2">
    <comp symbol="EQU" arg1="t1" arg2="now" from="12" to="15"></comp>
   </cond>
   <cond label="b2">
    <pred arg="e1" symbol="be" synset="be.v.01" from="12" to="15"></pred>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="t1" symbol="Time" framenet="Time" from="12" to="15"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x2" symbol="Co-Theme" framenet="Replacing@New" from="12" to="15"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x1" symbol="Theme" framenet="Placing@Theme" from="12" to="15"></rel>
   </cond>
   <cond label="b2">
    <pred arg="x2" symbol="vergnügungspark" synset="vergnügungspark.n.01" from="20" to="35"></pred>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/en/bronze/p00/d0066/en.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- I have run out of my traveling expenses . --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">I</tag>
     <tag type="cat">np</tag>
     <tag type="sym">speaker</tag>
     <tag type="lemma">speaker</tag>
     <tag type="from">0</tag>
     <tag type="to">1</tag>
     <tag type="pos">PRP</tag>
     <tag type="sem">PRO</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">have</tag>
     <tag type="cat">(s:dcl\np)/(s:pt\np)</tag>
     <tag type="sym">have</tag>
     <tag type="lemma">have</tag>
     <tag type="from">2</tag>
     <tag type="to">6</tag>
     <tag type="pos">VBP</tag>
     <tag type="sem">NEC</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="tok">run</tag>
     <tag type="cat">s:pt\np</tag>
     <tag type="sym">run</tag>
     <tag type="lemma">run</tag>
     <tag type="from">7</tag>
     <tag type="to">10</tag>
     <tag type="pos">VBN</tag>
     <tag type="sem">EXS</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">out</tag>
     <tag type="cat">((s:dcl\np)\(s:dcl\np))/pp</tag>
     <tag type="sym">out</tag>
     <tag type="lemma">out</tag>
     <tag type="from">11</tag>
     <tag type="to">14</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="tok">of</tag>
     <tag type="cat">pp/np</tag>
     <tag type="sym">of</tag>
     <tag type="lemma">of</tag>
     <tag type="from">15</tag>
     <tag type="to">17</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="tok">my</tag>
     <tag type="cat">np/(n/pp)</tag>
     <tag type="sym">speaker</tag>
     <tag type="lemma">speaker</tag>
     <tag type="from">18</tag>
     <tag type="to">20</tag>
     <tag type="pos">PRP$</tag>
     <tag type="sem">HAS</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Of]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="tok">traveling</tag>
     <tag type="cat">n/n</tag>
     <tag type="sym">travel</tag>
     <tag type="lemma">travel</tag>
     <tag type="from">21</tag>
     <tag type="to">30</tag>
     <tag type="pos">VBG</tag>
     <tag type="sem">EXG</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1008">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">expenses</tag>
     <tag type="cat">n/pp</tag>
     <tag type="sym">expense</tag>
     <tag type="lemma">expense</tag>
     <tag type="from">31</tag>
     <tag type="to">39</tag>
     <tag type="pos">NNS</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1009">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">.</tag>
     <tag type="cat">s:dcl\s:dcl</tag>
     <tag type="sym">.</tag>
     <tag type="lemma">.</tag>
     <tag type="from">39</tag>
     <tag type="to">40</tag>
     <tag type="pos">.</tag>
     <tag type="sem">NIL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b1">
  <domain>
   <dr label="b1" name="x1" from="0" to="1"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="x1" symbol="person" synset="person.n.01" from="0" to="1"></pred>
   </cond>
   <cond label="b1">
    <comp symbol="EQU" arg1="x1" arg2="speaker" from="0" to="1"></comp>
   </cond>
   <cond label="b1">
    <nec from="2" to="6">
     <drs label="b2">
      <domain>
       <dr label="b2" name="e1" from="7" to="10"></dr>
       <dr label="b2" name="x2" from="11" to="14"></dr>
       <dr label="b3" name="x3" from="18" to="20"></dr>
       <dr label="b3" name="e2" from="21" to="30"></dr>
      </domain>
      <conds>
       <cond label="b2">
        <pred arg="e1" symbol="run" synset="run.v.01" from="7" to="10"></pred>
       </cond>
       <cond label="b2">
        <rel arg1="e1" arg2="x2" symbol="Causer" framenet="Causer" from="11" to="14"></rel>
       </cond>
       <cond label="b2">
        <rel arg1="e1" arg2="x1" symbol="Theme" framenet="Impact@Impactor" from="7" to="10"></rel>
       </cond>
       <cond label="b2">
        <pred arg="x2" symbol="entity" synset="entity.n.01" from="11" to="14"></pred>
       </cond>
       <cond label="b2">
        <rel arg1="x2" arg2="x3" symbol="Theme" framenet="Emptying@Theme" from="15" to="17"></rel>
       </cond>
       <cond label="b3">
        <pred arg="x3" symbol="expense" synset="expense.n.01" from="31" to="39"></pred>
       </cond>
       <cond label="b3">
        <rel arg1="x3" arg2="speaker" symbol="Of" framenet="Of" from="18" to="20"></rel>
       </cond>
       <cond label="b3">
        <pred arg="e2" symbol="travel" synset="travel.v.01" from="21" to="30"></pred>
       </cond>
       <cond label="b3">
        <rel arg1="e2" arg2="x3" symbol="Theme" framenet="Theme" from="21" to="30"></rel>
       </cond>
      </conds>
     </drs>
    </nec>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/it/gold/p00/d0717/it.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- I Yakuza sono la mafia giapponese . --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">I</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">the</tag>
     <tag type="lemma">the</tag>
     <tag type="from">0</tag>
     <tag type="to">1</tag>
     <tag type="sem">DEF</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">Yakuza</tag>
     <tag type="cat">n</tag>
     <tag type="sym">yakuza</tag>
     <tag type="lemma">yakuza</tag>
     <tag type="from">2</tag>
     <tag type="to">8</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">yakuza.n.02</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="tok">sono</tag>
     <tag type="cat">(s:dcl\np)/np</tag>
     <tag type="sym">be</tag>
     <tag type="lemma">be</tag>
     <tag type="from">9</tag>
     <tag type="to">13</tag>
     <tag type="sem">ENS</tag>
     <tag type="wordnet">be.v.02</tag>
     <tag type="verbnet" n="2">[Co-Theme,Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">la</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">the</tag>
     <tag type="lemma">the</tag>
     <tag type="from">14</tag>
     <tag type="to">16</tag>
     <tag type="sem">DEF</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">mafia</tag>
     <tag type="cat">n</tag>
     <tag type="sym">mafia</tag>
     <tag type="lemma">mafia</tag>
     <tag type="from">17</tag>
     <tag type="to">22</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">mafia.n.01</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="tok">giapponese</tag>
     <tag type="cat">n\n</tag>
     <tag type="sym">japan</tag>
     <tag type="lemma">japan</tag>
     <tag type="from">23</tag>
     <tag type="to">33</tag>
     <tag type="sem">GPO</tag>
     <tag type="wordnet">country.n.02</tag>
     <tag type="verbnet" n="1">[Location]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">.</tag>
     <tag type="cat">s:dcl\s:dcl</tag>
     <tag type="sym">.</tag>
     <tag type="lemma">.</tag>
     <tag type="from">33</tag>
     <tag type="to">34</tag>
     <tag type="sem">NIL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b4">
  <domain>
   <dr label="b1" name="x1" from="0" to="1"></dr>
   <dr label="b2" name="x2" from="14" to="16"></dr>
   <dr label="b3" name="x3" from="23" to="33"></dr>
   <dr label="b4" name="e1" from="9" to="13"></dr>
   <dr label="b4" name="t1" from="9" to="13"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="x1" symbol="yakuza" synset="yakuza.n.02" from="2" to="8"></pred>
   </cond>
   <cond label="b4">
    <pred arg="t1" symbol="time" synset="time.n.08" from="9" to="13"></pred>
   </cond>
   <cond label="b4">
    <comp symbol="EQU" arg1="t1" arg2="now" from="9" to="13"></comp>
   </cond>
   <cond label="b4">
    <pred arg="e1" symbol="be" synset="be.v.02" from="9" to="13"></pred>
   </cond>
   <cond label="b4">
    <rel arg1="e1" arg2="t1" symbol="Time" framenet="Time" from="9" to="13"></rel>
   </cond>
   <cond label="b4">
    <rel arg1="e1" arg2="x2" symbol="Co-Theme" framenet="Replacing@New" from="9" to="13"></rel>
   </cond>
   <cond label="b4">
    <rel arg1="e1" arg2="x1" symbol="Theme" framenet="Placing@Theme" from="9" to="13"></rel>
   </cond>
   <cond label="b2">
    <pred arg="x2" symbol="mafia" synset="mafia.n.01" from="17" to="22"></pred>
   </cond>
   <cond label="b2">
    <rel arg1="x2" arg2="x3" symbol="Location" framenet="Location" from="23" to="33"></rel>
   </cond>
   <cond label="b3">
    <pred arg="x3" symbol="country" synset="country.n.02" from="23" to="33"></pred>
   </cond>
   <cond label="b3">
    <named arg="x3" symbol="japan" from="23" to="33"></named>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>
