=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/dtd/xdrs.dtd
<!-- begin parameter entities -->
<!ENTITY % drsexp "(var|app|drs|smerge|merge|alfa|sdrs)">
<!-- end parameter entities -->

<!-- drs -->
<!ELEMENT xdrs-output (xdrs*)>
<!ATTLIST xdrs-output  
          version CDATA #REQUIRED >

<!ELEMENT xdrs (taggedtokens,(sdrs|app|drs|smerge|merge|alfa))>
<!ATTLIST xdrs
          xml:id ID #IMPLIED >

<!ELEMENT sdrs (constituents,relations)>

<!ELEMENT constituents ((sub|constituent)+)> <!-- (sub|constituent+)> -->

<!ELEMENT sub (constituent,(sdrs|constituent))> <!-- was (constituent+)> -->

<!ELEMENT constituent (tokens?, (drs|sub))> <!-- was (tokens?, drs) -->
<!ATTLIST constituent 
          label CDATA #REQUIRED>

<!ELEMENT relations (drel*)>

<!ELEMENT drel EMPTY>
<!ATTLIST drel 
          arg1 CDATA #REQUIRED 
          arg2 CDATA #REQUIRED 
          sym CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED >
          
<!-- begin taggedtokens -->
<!ELEMENT taggedtokens (tagtoken+)>

<!ELEMENT tagtoken (tags)>
<!ATTLIST tagtoken 
          xml:id ID #REQUIRED>

<!ELEMENT tags (tag+)>

<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag 
          type (verbnet|tok|wordnet|cat|sense|sym|lemma|sem|from|to|pos|antecedent) #REQUIRED>
<!ATTLIST tag 
          n CDATA #IMPLIED>
<!-- end taggedtokens -->             

<!ELEMENT drs (domain,conds)>
<!-- <!ATTLIST drs
          type CDATA #REQUIRED > -->
<!ATTLIST drs
          label CDATA #REQUIRED >          

<!ELEMENT tokens (token*)> <!-- to remove --> 

<!ELEMENT token (#PCDATA)>

<!ELEMENT domain (dr*)>

<!ELEMENT conds (cond*)>

<!ELEMENT cond (named|pred|rel|comp|prop|not|nec|pos|or|imp|whq|duplex)>
<!ATTLIST cond
          label CDATA #REQUIRED > 

<!--<!ELEMENT conds ((timex|named|pred|card|eq|rel|prop|not|nec|pos|or|imp|whq)*)>-->

<!ELEMENT merge (%drsexp;,%drsexp;)>

<!ELEMENT smerge (%drsexp;,%drsexp;)>

<!ELEMENT lam ((var,%drsexp;)|(var,lam)|var)>

<!ELEMENT app (lam,%drsexp;)>

<!ELEMENT alfa (%drsexp;,%drsexp;)>
<!ATTLIST alfa
          type CDATA #REQUIRED >

<!ELEMENT index (#PCDATA)>
<!ATTLIST index
          pos CDATA #REQUIRED >

<!ELEMENT var (#PCDATA)>

<!ELEMENT dr (index*)>
<!ATTLIST dr
          label CDATA #REQUIRED
          name CDATA #REQUIRED 
          from CDATA #REQUIRED 
          to CDATA #REQUIRED>

<!ELEMENT pred (index*)>
<!ATTLIST pred
          arg CDATA #REQUIRED 
          symbol CDATA #REQUIRED 
          synset CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT named (index*)>
<!ATTLIST named
          arg CDATA #REQUIRED 
          symbol CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT rel (index*)>
<!ATTLIST rel
          arg1 CDATA #REQUIRED 
          arg2 CDATA #REQUIRED 
          symbol CDATA #REQUIRED
          framenet CDATA #IMPLIED 
          sense CDATA #IMPLIED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT comp (index*)>
<!ATTLIST comp
          arg1 CDATA #REQUIRED 
          arg2 CDATA #REQUIRED 
          symbol CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>


<!ELEMENT not (index*,%drsexp;)>
<!ATTLIST not
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT pos (index*,%drsexp;)>
<!ATTLIST pos
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT nec (index*,%drsexp;)>
<!ATTLIST nec
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT or (index*,(%drsexp;,%drsexp;))>
<!ATTLIST or
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT imp (index*,(%drsexp;,%drsexp;))>
<!ATTLIST imp
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT whq (index*,(%drsexp;,%drsexp;))>

<!ELEMENT duplex (index*,(%drsexp;,%drsexp;))>
<!ATTLIST duplex
		  type CDATA #REQUIRED
		  var CDATA #REQUIRED 	
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT prop (index*,%drsexp;)>
<!ATTLIST prop
          argument CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED >

<!ELEMENT timex (index*,(date|time))>
<!ATTLIST timex
          arg CDATA #REQUIRED >

<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>

<!ELEMENT words (word+)>
<!ELEMENT word (#PCDATA)>
<!ATTLIST word
          xml:id ID #REQUIRED >

<!ELEMENT postags (postag+)>
<!ELEMENT postag (#PCDATA)>
<!ATTLIST postag
          index IDREF #REQUIRED >

<!ELEMENT netags (netag*)>
<!ELEMENT netag (#PCDATA)>
<!ATTLIST netag
          index IDREF #REQUIRED >

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/en/silver/p00/d0008/en.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- A dog with a golden coat is in the water --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">A</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">a</tag>
     <tag type="lemma">a</tag>
     <tag type="from">0</tag>
     <tag type="to">1</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DIS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">dog</tag>
     <tag type="cat">n</tag>
     <tag type="sym">dog</tag>
     <tag type="lemma">dog</tag>
     <tag type="from">2</tag>
     <tag type="to">5</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">dog.n.01</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="tok">with</tag>
     <tag type="cat">(n\n)/np</tag>
     <tag type="sym">with</tag>
     <tag type="lemma">with</tag>
     <tag type="from">6</tag>
     <tag type="to">10</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Instrument]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">a</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">a</tag>
     <tag type="lemma">a</tag>
     <tag type="from">11</tag>
     <tag type="to">12</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DIS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="tok">golden</tag>
     <tag type="cat">n/n</tag>
     <tag type="sym">golden</tag>
     <tag type="lemma">golden</tag>
     <tag type="from">13</tag>
     <tag type="to">19</tag>
     <tag type="pos">JJ</tag>
     <tag type="sem">IST</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Attribute]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">coat</tag>
     <tag type="cat">n</tag>
     <tag type="sym">coat</tag>
     <tag type="lemma">coat</tag>
     <tag type="from">20</tag>
     <tag type="to">24</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">coat.n.03</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="tok">is</tag>
     <tag type="cat">(s:dcl\np)/pp</tag>
     <tag type="sym">be</tag>
     <tag type="lemma">be</tag>
     <tag type="from">25</tag>
     <tag type="to">27</tag>
     <tag type="pos">VBZ</tag>
     <tag type="sem">ENS</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1008">
   <tags>
     <tag type="tok">in</tag>
     <tag type="cat">pp/np</tag>
     <tag type="sym">in</tag>
     <tag type="lemma">in</tag>
     <tag type="from">28</tag>
     <tag type="to">30</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Location]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1009">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">the</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">the</tag>
     <tag type="lemma">the</tag>
     <tag type="from">31</tag>
     <tag type="to">34</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DEF</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1010">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">water</tag>
     <tag type="cat">n</tag>
     <tag type="sym">water</tag>
     <tag type="lemma">water</tag>
     <tag type="from">35</tag>
     <tag type="to">40</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">water.n.02</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b1">
  <domain>
   <dr label="b1" name="x1" from="0" to="1"></dr>
   <dr label="b1" name="x2" from="11" to="12"></dr>
   <dr label="b1" name="s1" from="13" to="19"></dr>
   <dr label="b1" name="e1" from="25" to="27"></dr>
   <dr label="b2" name="x3" from="31" to="34"></dr>
   <dr label="b1" name="t1" from="25" to="27"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="x1" symbol="dog" synset="dog.n.01" from="2" to="5"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="x1" arg2="x2" symbol="Instrument" framenet="Instrument" from="6" to="10"></rel>
   </cond>
   <cond label="b1">
    <pred arg="s1" symbol="golden" synset="golden.a.01" from="13" to="19"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="s1" arg2="x2" symbol="AttributeOf" framenet="AttributeOf" from="13" to="19"></rel>
   </cond>
   <cond label="b1">
    <pred arg="x2" symbol="coat" synset="coat.n.03" from="20" to="24"></pred>
   </cond>
   <cond label="b1">
    <pred arg="t1" symbol="time" synset="time.n.08" from="25" to="27"></pred>
   </cond>
   <cond label="b1">
    <comp symbol="EQU" arg1="t1" arg2="now" from="25" to="27"></comp>
   </cond>
   <cond label="b1">
    <pred arg="e1" symbol="be" synset="be.v.01" from="25" to="27"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="t1" symbol="Time" framenet="Time" from="25" to="27"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x3" symbol="Location" framenet="Containing@Container" from="28" to="30"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x1" symbol="Theme" framenet="Placing@Theme" from="25" to="27"></rel>
   </cond>
   <cond label="b2">
    <pred arg="x3" symbol="water" synset="water.n.02" from="35" to="40"></pred>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/en/silver/p00/d0002/en.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- A blond boy is walking up a sand dune with a skateboard --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">A</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">a</tag>
     <tag type="lemma">a</tag>
     <tag type="from">0</tag>
     <tag type="to">1</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DIS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="tok">blond</tag>
     <tag type="cat">n/n</tag>
     <tag type="sym">blond</tag>
     <tag type="lemma">blond</tag>
     <tag type="from">2</tag>
     <tag type="to">7</tag>
     <tag type="pos">JJ</tag>
     <tag type="sem">IST</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Attribute]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">boy</tag>
     <tag type="cat">n</tag>
     <tag type="sym">boy</tag>
     <tag type="lemma">boy</tag>
     <tag type="from">8</tag>
     <tag type="to">11</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">boy.n.01</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">is</tag>
     <tag type="cat">(s:dcl\np)/(s:ng\np)</tag>
     <tag type="sym">be</tag>
     <tag type="lemma">be</tag>
     <tag type="from">12</tag>
     <tag type="to">14</tag>
     <tag type="pos">VBZ</tag>
     <tag type="sem">NOW</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="tok">walking</tag>
     <tag type="cat">((s:ng\np)/np)/pr</tag>
     <tag type="sym">walk</tag>
     <tag type="lemma">walk</tag>
     <tag type="from">15</tag>
     <tag type="to">22</tag>
     <tag type="pos">VBG</tag>
     <tag type="sem">EXG</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">up</tag>
     <tag type="cat">pr</tag>
     <tag type="sym">up</tag>
     <tag type="lemma">up</tag>
     <tag type="from">23</tag>
     <tag type="to">25</tag>
     <tag type="pos">RP</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">a</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">a</tag>
     <tag type="lemma">a</tag>
     <tag type="from">26</tag>
     <tag type="to">27</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DIS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1008">
   <tags>
     <tag type="tok">sand</tag>
     <tag type="cat">n/n</tag>
     <tag type="sym">sand</tag>
     <tag type="lemma">sand</tag>
     <tag type="from">28</tag>
     <tag type="to">32</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[MadeOf]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1009">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">dune</tag>
     <tag type="cat">n</tag>
     <tag type="sym">dune</tag>
     <tag type="lemma">dune</tag>
     <tag type="from">33</tag>
     <tag type="to">37</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1010">
   <tags>
     <tag type="tok">with</tag>
     <tag type="cat">((s:dcl\np)\(s:dcl\np))/np</tag>
     <tag type="sym">with</tag>
     <tag type="lemma">with</tag>
     <tag type="from">38</tag>
     <tag type="to">42</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Instrument]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1011">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">a</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">a</tag>
     <tag type="lemma">a</tag>
     <tag type="from">43</tag>
     <tag type="to">44</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DIS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1012">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">skateboard</tag>
     <tag type="cat">n</tag>
     <tag type="sym">skateboard</tag>
     <tag type="lemma">skateboard</tag>
     <tag type="from">45</tag>
     <tag type="to">55</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">skateboard.n.01</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b1">
  <domain>
   <dr label="b1" name="x1" from="0" to="1"></dr>
   <dr label="b1" name="s1" from="2" to="7"></dr>
   <dr label="b1" name="x2" from="26" to="27"></dr>
   <dr label="b1" name="x3" from="28" to="32"></dr>
   <dr label="b1" name="e1" from="15" to="22"></dr>
   <dr label="b1" name="t1" from="12" to="14"></dr>
   <dr label="b1" name="x4" from="43" to="44"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="s1" symbol="blond" synset="blond.a.01" from="2" to="7"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="s1" arg2="x1" symbol="AttributeOf" framenet="AttributeOf" from="2" to="7"></rel>
   </cond>
   <cond label="b1">
    <pred arg="x1" symbol="boy" synset="boy.n.01" from="8" to="11"></pred>
   </cond>
   <cond label="b1">
    <pred arg="t1" symbol="time" synset="time.n.08" from="12" to="14"></pred>
   </cond>
   <cond label="b1">
    <comp symbol="EQU" arg1="t1" arg2="now" from="12" to="14"></comp>
   </cond>
   <cond label="b1">
    <pred arg="e1" symbol="walk" synset="walk.v.01" from="15" to="22"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x4" symbol="Instrument" framenet="Reshaping@Instrument" from="38" to="42"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="t1" symbol="Time" framenet="Time" from="12" to="14"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x2" symbol="Path" framenet="Path" from="15" to="22"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x1" symbol="Theme" framenet="Theme" from="15" to="22"></rel>
   </cond>
   <cond label="b1">
    <pred arg="x3" symbol="sand" synset="sand.n.01" from="28" to="32"></pred>
   </cond>
   <cond label="b1">
    <pred arg="x2" symbol="dune" synset="dune.n.01" from="33" to="37"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="x2" arg2="x3" symbol="MadeOf" framenet="MadeOf" from="28" to="32"></rel>
   </cond>
   <cond label="b1">
    <pred arg="x4" symbol="skateboard" synset="skateboard.n.01" from="45" to="55"></pred>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/en/silver/p00/d0003/en.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- A boy is running through the sand --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">A</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">a</tag>
     <tag type="lemma">a</tag>
     <tag type="from">0</tag>
     <tag type="to">1</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DIS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">boy</tag>
     <tag type="cat">n</tag>
     <tag type="sym">boy</tag>
     <tag type="lemma">boy</tag>
     <tag type="from">2</tag>
     <tag type="to">5</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">boy.n.01</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">is</tag>
     <tag type="cat">(s:dcl\np)/(s:ng\np)</tag>
     <tag type="sym">be</tag>
     <tag type="lemma">be</tag>
     <tag type="from">6</tag>
     <tag type="to">8</tag>
     <tag type="pos">VBZ</tag>
     <tag type="sem">NOW</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="tok">running</tag>
     <tag type="cat">s:ng\np</tag>
     <tag type="sym">run</tag>
     <tag type="lemma">run</tag>
     <tag type="from">9</tag>
     <tag type="to">16</tag>
     <tag type="pos">VBG</tag>
     <tag type="sem">EXG</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="tok">through</tag>
     <tag type="cat">((s:dcl\np)\(s:dcl\np))/np</tag>
     <tag type="sym">through</tag>
     <tag type="lemma">through</tag>
     <tag type="from">17</tag>
     <tag type="to">24</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Path]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">the</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">the</tag>
     <tag type="lemma">the</tag>
     <tag type="from">25</tag>
     <tag type="to">28</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DEF</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">sand</tag>
     <tag type="cat">n</tag>
     <tag type="sym">sand</tag>
     <tag type="lemma">sand</tag>
     <tag type="from">29</tag>
     <tag type="to">33</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">sand.n.01</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b1">
  <domain>
   <dr label="b1" name="x1" from="0" to="1"></dr>
   <dr label="b1" name="e1" from="9" to="16"></dr>
   <dr label="b1" name="t1" from="6" to="8"></dr>
   <dr label="b2" name="x2" from="25" to="28"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="x1" symbol="boy" synset="boy.n.01" from="2" to="5"></pred>
   </cond>
   <cond label="b1">
    <pred arg="t1" symbol="time" synset="time.n.08" from="6" to="8"></pred>
   </cond>
   <cond label="b1">
    <comp symbol="EQU" arg1="t1" arg2="now" from="6" to="8"></comp>
   </cond>
   <cond label="b1">
    <pred arg="e1" symbol="run" synset="run.v.01" from="9" to="16"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x2" symbol="Path" framenet="Path" from="17" to="24"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="t1" symbol="Time" framenet="Time" from="6" to="8"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x1" symbol="Theme" framenet="Impact@Impactor" from="9" to="16"></rel>
   </cond>
   <cond label="b2">
    <pred arg="x2" symbol="sand" synset="sand.n.01" from="29" to="33"></pred>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/nl/gold/p00/d0780/nl.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 10 September 2021, 09:36:38)'">
<!-- De astronauten gingen naar de maan in een raket . --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">De</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">the</tag>
     <tag type="lemma">the</tag>
     <tag type="from">0</tag>
     <tag type="to">2</tag>
     <tag type="sem">DEF</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">astronauten</tag>
     <tag type="cat">n</tag>
     <tag type="sym">astronaut</tag>
     <tag type="lemma">astronaut</tag>
     <tag type="from">3</tag>
     <tag type="to">14</tag>
     <tag type="sem">ROL</tag>
     <tag type="wordnet">astronaut.n.01</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="tok">gingen</tag>
     <tag type="cat">(s:dcl\np)/pp</tag>
     <tag type="sym">go</tag>
     <tag type="lemma">go</tag>
     <tag type="from">15</tag>
     <tag type="to">21</tag>
     <tag type="sem">EPS</tag>
     <tag type="wordnet">go.v.01</tag>
     <tag type="verbnet" n="1">[Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="tok">naar</tag>
     <tag type="cat">pp/np</tag>
     <tag type="sym">to</tag>
     <tag type="lemma">to</tag>
     <tag type="from">22</tag>
     <tag type="to">26</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Destination]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">de</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">the</tag>
     <tag type="lemma">the</tag>
     <tag type="from">27</tag>
     <tag type="to">29</tag>
     <tag type="sem">DEF</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">maan</tag>
     <tag type="cat">n</tag>
     <tag type="sym">moon</tag>
     <tag type="lemma">moon</tag>
     <tag type="from">30</tag>
     <tag type="to">34</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">moon.n.01</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="tok">in</tag>
     <tag type="cat">((s:dcl\np)\(s:dcl\np))/np</tag>
     <tag type="sym">in</tag>
     <tag type="lemma">in</tag>
     <tag type="from">35</tag>
     <tag type="to">37</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Instrument]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1008">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">een</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">a</tag>
     <tag type="lemma">a</tag>
     <tag type="from">38</tag>
     <tag type="to">41</tag>
     <tag type="sem">DIS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1009">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">raket</tag>
     <tag type="cat">n</tag>
     <tag type="sym">rocket</tag>
     <tag type="lemma">rocket</tag>
     <tag type="from">42</tag>
     <tag type="to">47</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">rocket.n.01</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1010">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">.</tag>
     <tag type="cat">s:dcl\s:dcl</tag>
     <tag type="sym">.</tag>
     <tag type="lemma">.</tag>
     <tag type="from">47</tag>
     <tag type="to">48</tag>
     <tag type="sem">NIL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b2">
  <domain>
   <dr label="b1" name="x1" from="0" to="2"></dr>
   <dr label="b1" name="x2" from="3" to="14"></dr>
   <dr label="b2" name="e1" from="15" to="21"></dr>
   <dr label="b3" name="x3" from="27" to="29"></dr>
   <dr label="b2" name="t1" from="15" to="21"></dr>
   <dr label="b2" name="x4" from="38" to="41"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="x2" symbol="astronaut" synset="astronaut.n.01" from="3" to="14"></pred>
   </cond>
   <cond label="b1">
    <pred arg="x1" symbol="person" synset="person.n.01" from="3" to="14"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="x1" arg2="x2" symbol="Role" framenet="Role" from="3" to="14"></rel>
   </cond>
   <cond label="b2">
    <pred arg="t1" symbol="time" synset="time.n.08" from="15" to="21"></pred>
   </cond>
   <cond label="b2">
    <comp symbol="TPR" arg1="t1" arg2="now" from="15" to="21"></comp>
   </cond>
   <cond label="b2">
    <pred arg="e1" symbol="go" synset="go.v.01" from="15" to="21"></pred>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x4" symbol="Instrument" framenet="Apply_heat@Heating_instrument" from="35" to="37"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="t1" symbol="Time" framenet="Time" from="15" to="21"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x3" symbol="Destination" framenet="Removing@Goal" from="22" to="26"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x1" symbol="Theme" framenet="Self_motion@Self_mover" from="15" to="21"></rel>
   </cond>
   <cond label="b3">
    <pred arg="x3" symbol="moon" synset="moon.n.01" from="30" to="34"></pred>
   </cond>
   <cond label="b2">
    <pred arg="x4" symbol="rocket" synset="rocket.n.01" from="42" to="47"></pred>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>
