=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/dtd/xdrs.dtd
<!-- begin parameter entities -->
<!ENTITY % drsexp "(var|app|drs|smerge|merge|alfa|sdrs)">
<!-- end parameter entities -->

<!-- drs -->
<!ELEMENT xdrs-output (xdrs*)>
<!ATTLIST xdrs-output  
          version CDATA #REQUIRED >

<!ELEMENT xdrs (taggedtokens,(sdrs|app|drs|smerge|merge|alfa))>
<!ATTLIST xdrs
          xml:id ID #IMPLIED >

<!ELEMENT sdrs (constituents,relations)>

<!ELEMENT constituents ((sub|constituent)+)> <!-- (sub|constituent+)> -->

<!ELEMENT sub (constituent,(sdrs|constituent))> <!-- was (constituent+)> -->

<!ELEMENT constituent (tokens?, (drs|sub))> <!-- was (tokens?, drs) -->
<!ATTLIST constituent 
          label CDATA #REQUIRED>

<!ELEMENT relations (drel*)>

<!ELEMENT drel EMPTY>
<!ATTLIST drel 
          arg1 CDATA #REQUIRED 
          arg2 CDATA #REQUIRED 
          sym CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED >
          
<!-- begin taggedtokens -->
<!ELEMENT taggedtokens (tagtoken+)>

<!ELEMENT tagtoken (tags)>
<!ATTLIST tagtoken 
          xml:id ID #REQUIRED>

<!ELEMENT tags (tag+)>

<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag 
          type (verbnet|tok|wordnet|cat|sense|sym|lemma|sem|from|to|pos|antecedent) #REQUIRED>
<!ATTLIST tag 
          n CDATA #IMPLIED>
<!-- end taggedtokens -->             

<!ELEMENT drs (domain,conds)>
<!-- <!ATTLIST drs
          type CDATA #REQUIRED > -->
<!ATTLIST drs
          label CDATA #REQUIRED >          

<!ELEMENT tokens (token*)> <!-- to remove --> 

<!ELEMENT token (#PCDATA)>

<!ELEMENT domain (dr*)>

<!ELEMENT conds (cond*)>

<!ELEMENT cond (named|pred|rel|comp|prop|not|nec|pos|or|imp|whq|duplex)>
<!ATTLIST cond
          label CDATA #REQUIRED > 

<!--<!ELEMENT conds ((timex|named|pred|card|eq|rel|prop|not|nec|pos|or|imp|whq)*)>-->

<!ELEMENT merge (%drsexp;,%drsexp;)>

<!ELEMENT smerge (%drsexp;,%drsexp;)>

<!ELEMENT lam ((var,%drsexp;)|(var,lam)|var)>

<!ELEMENT app (lam,%drsexp;)>

<!ELEMENT alfa (%drsexp;,%drsexp;)>
<!ATTLIST alfa
          type CDATA #REQUIRED >

<!ELEMENT index (#PCDATA)>
<!ATTLIST index
          pos CDATA #REQUIRED >

<!ELEMENT var (#PCDATA)>

<!ELEMENT dr (index*)>
<!ATTLIST dr
          label CDATA #REQUIRED
          name CDATA #REQUIRED 
          from CDATA #REQUIRED 
          to CDATA #REQUIRED>

<!ELEMENT pred (index*)>
<!ATTLIST pred
          arg CDATA #REQUIRED 
          symbol CDATA #REQUIRED 
          synset CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT named (index*)>
<!ATTLIST named
          arg CDATA #REQUIRED 
          symbol CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT rel (index*)>
<!ATTLIST rel
          arg1 CDATA #REQUIRED 
          arg2 CDATA #REQUIRED 
          symbol CDATA #REQUIRED
          framenet CDATA #IMPLIED 
          sense CDATA #IMPLIED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT comp (index*)>
<!ATTLIST comp
          arg1 CDATA #REQUIRED 
          arg2 CDATA #REQUIRED 
          symbol CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED>


<!ELEMENT not (index*,%drsexp;)>
<!ATTLIST not
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT pos (index*,%drsexp;)>
<!ATTLIST pos
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT nec (index*,%drsexp;)>
<!ATTLIST nec
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT or (index*,(%drsexp;,%drsexp;))>
<!ATTLIST or
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT imp (index*,(%drsexp;,%drsexp;))>
<!ATTLIST imp
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT whq (index*,(%drsexp;,%drsexp;))>

<!ELEMENT duplex (index*,(%drsexp;,%drsexp;))>
<!ATTLIST duplex
		  type CDATA #REQUIRED
		  var CDATA #REQUIRED 	
          from CDATA #IMPLIED
          to CDATA #IMPLIED>

<!ELEMENT prop (index*,%drsexp;)>
<!ATTLIST prop
          argument CDATA #REQUIRED 
          from CDATA #IMPLIED
          to CDATA #IMPLIED >

<!ELEMENT timex (index*,(date|time))>
<!ATTLIST timex
          arg CDATA #REQUIRED >

<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>

<!ELEMENT words (word+)>
<!ELEMENT word (#PCDATA)>
<!ATTLIST word
          xml:id ID #REQUIRED >

<!ELEMENT postags (postag+)>
<!ELEMENT postag (#PCDATA)>
<!ATTLIST postag
          index IDREF #REQUIRED >

<!ELEMENT netags (netag*)>
<!ELEMENT netag (#PCDATA)>
<!ATTLIST netag
          index IDREF #REQUIRED >

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/nl/silver/p00/d0714/nl.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- ø Computers worden ø gebruikt om te voorzien in ø gezondheidsinformatie . --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">ø</tag>
     <tag type="cat">np/n</tag>
     <tag type="wordnet">O</tag>
     <tag type="sense">0</tag>
     <tag type="sym">ø</tag>
     <tag type="lemma">ø</tag>
     <tag type="sem">DEF</tag>
     <tag type="from">0</tag>
     <tag type="to">-1</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">Computers</tag>
     <tag type="cat">n</tag>
     <tag type="sym">computers</tag>
     <tag type="lemma">computers</tag>
     <tag type="from">0</tag>
     <tag type="to">9</tag>
     <tag type="sem">PER</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">worden</tag>
     <tag type="cat">(s:dcl\np)/(s:adj\np)</tag>
     <tag type="sym">worden</tag>
     <tag type="lemma">worden</tag>
     <tag type="from">10</tag>
     <tag type="to">16</tag>
     <tag type="sem">NOW</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">ø</tag>
     <tag type="cat">(s:dcl/s:dcl)/(s:pss\np)</tag>
     <tag type="wordnet">O</tag>
     <tag type="sense">0</tag>
     <tag type="sym">ø</tag>
     <tag type="lemma">ø</tag>
     <tag type="sem">REL</tag>
     <tag type="from">17</tag>
     <tag type="to">-1</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">gebruikt</tag>
     <tag type="cat">s:pss\np</tag>
     <tag type="sym">gebruikt</tag>
     <tag type="lemma">gebruikt</tag>
     <tag type="from">17</tag>
     <tag type="to">25</tag>
     <tag type="sem">EXS</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">om</tag>
     <tag type="cat">(s:adj\np)/((s:to\np)/np)</tag>
     <tag type="sym">om</tag>
     <tag type="lemma">om</tag>
     <tag type="from">26</tag>
     <tag type="to">28</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">te</tag>
     <tag type="cat">(s:to\np)/(s:b\np)</tag>
     <tag type="sym">te</tag>
     <tag type="lemma">te</tag>
     <tag type="from">29</tag>
     <tag type="to">31</tag>
     <tag type="sem">INT</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1008">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">voorzien</tag>
     <tag type="cat">(s:b\np)/np</tag>
     <tag type="sym">voorzien</tag>
     <tag type="lemma">voorzien</tag>
     <tag type="from">32</tag>
     <tag type="to">40</tag>
     <tag type="sem">IST</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1009">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">in</tag>
     <tag type="cat">((s:b\np)\(s:b\np))/np</tag>
     <tag type="sym">in</tag>
     <tag type="lemma">in</tag>
     <tag type="from">41</tag>
     <tag type="to">43</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1010">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">ø</tag>
     <tag type="cat">np/n</tag>
     <tag type="wordnet">O</tag>
     <tag type="sense">0</tag>
     <tag type="sym">ø</tag>
     <tag type="lemma">ø</tag>
     <tag type="sem">DIS</tag>
     <tag type="from">44</tag>
     <tag type="to">-1</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1011">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">gezondheidsinformatie</tag>
     <tag type="cat">n</tag>
     <tag type="sym">gezondheidsinformatie</tag>
     <tag type="lemma">gezondheidsinformatie</tag>
     <tag type="from">44</tag>
     <tag type="to">65</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1012">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">.</tag>
     <tag type="cat">s:dcl\s:dcl</tag>
     <tag type="sym">.</tag>
     <tag type="lemma">.</tag>
     <tag type="from">65</tag>
     <tag type="to">66</tag>
     <tag type="sem">NIL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b1">
  <domain>
   <dr label="b1" name="x1" from="0" to="0"></dr>
   <dr label="b1" name="e1" from="17" to="25"></dr>
   <dr label="b2" name="x2" from="0" to="-1"></dr>
   <dr label="b1" name="x3" from="26" to="28"></dr>
   <dr label="b1" name="s1" from="32" to="40"></dr>
   <dr label="b1" name="x4" from="44" to="-1"></dr>
   <dr label="b1" name="s2" from="29" to="31"></dr>
   <dr label="b1" name="t1" from="10" to="16"></dr>
  </domain>
  <conds>
   <cond label="b2">
    <pred arg="x2" symbol="person" synset="person.n.01" from="0" to="9"></pred>
   </cond>
   <cond label="b2">
    <named arg="x2" symbol="computers" from="0" to="9"></named>
   </cond>
   <cond label="b1">
    <pred arg="s1" symbol="voorzien" synset="voorzien.a.01" from="32" to="40"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="s1" arg2="e1" symbol="Participant" framenet="Participant" from="0" to="0"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="s1" arg2="t1" symbol="Time" framenet="Time" from="10" to="16"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="s1" arg2="s2" symbol="Degree" framenet="Degree" from="29" to="31"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="s1" arg2="x4" symbol="Instrument" framenet="Apply_heat@Heating_instrument" from="41" to="43"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="s1" arg2="x2" symbol="Theme" framenet="Theme" from="32" to="40"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="s1" arg2="x3" symbol="Agent" framenet="Agent" from="32" to="40"></rel>
   </cond>
   <cond label="b1">
    <pred arg="t1" symbol="time" synset="time.n.08" from="10" to="16"></pred>
   </cond>
   <cond label="b1">
    <comp symbol="EQU" arg1="t1" arg2="now" from="10" to="16"></comp>
   </cond>
   <cond label="b1">
    <pred arg="e1" symbol="gebruikt" synset="gebruikt.v.01" from="17" to="25"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x1" symbol="Theme" framenet="Placing@Theme" from="17" to="25"></rel>
   </cond>
   <cond label="b1">
    <pred arg="x3" symbol="entity" synset="entity.n.01" from="26" to="28"></pred>
   </cond>
   <cond label="b1">
    <pred arg="s2" symbol="te" synset="te.r.01" from="29" to="31"></pred>
   </cond>
   <cond label="b1">
    <pred arg="x4" symbol="gezondheidsinformatie" synset="gezondheidsinformatie.n.01" from="44" to="65"></pred>
   </cond>
   <cond label="b1">
    <pred arg="x1" symbol="entity" synset="entity.n.01" from="0" to="0"></pred>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/en/bronze/p00/d0074/en.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- ø Frank was waiting with ø pleasure for the date in the evening . --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">ø</tag>
     <tag type="cat">np/n</tag>
     <tag type="wordnet">O</tag>
     <tag type="sense">0</tag>
     <tag type="sym">ø</tag>
     <tag type="lemma">ø</tag>
     <tag type="sem">DEF</tag>
     <tag type="from">0</tag>
     <tag type="to">-1</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">Frank</tag>
     <tag type="cat">n</tag>
     <tag type="sym">frank</tag>
     <tag type="lemma">frank</tag>
     <tag type="from">0</tag>
     <tag type="to">5</tag>
     <tag type="pos">NNP</tag>
     <tag type="sem">PER</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">was</tag>
     <tag type="cat">(s:dcl\np)/(s:ng\np)</tag>
     <tag type="sym">be</tag>
     <tag type="lemma">be</tag>
     <tag type="from">6</tag>
     <tag type="to">9</tag>
     <tag type="pos">VBD</tag>
     <tag type="sem">PST</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="tok">waiting</tag>
     <tag type="cat">(s:ng\np)/pp</tag>
     <tag type="sym">wait</tag>
     <tag type="lemma">wait</tag>
     <tag type="from">10</tag>
     <tag type="to">17</tag>
     <tag type="pos">VBG</tag>
     <tag type="sem">EXG</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Location]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="tok">with</tag>
     <tag type="cat">pp/np</tag>
     <tag type="sym">with</tag>
     <tag type="lemma">with</tag>
     <tag type="from">18</tag>
     <tag type="to">22</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Theme]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">ø</tag>
     <tag type="cat">np/n</tag>
     <tag type="wordnet">O</tag>
     <tag type="sense">0</tag>
     <tag type="sym">ø</tag>
     <tag type="lemma">ø</tag>
     <tag type="sem">DIS</tag>
     <tag type="from">23</tag>
     <tag type="to">-1</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">pleasure</tag>
     <tag type="cat">n</tag>
     <tag type="sym">pleasure</tag>
     <tag type="lemma">pleasure</tag>
     <tag type="from">23</tag>
     <tag type="to">31</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1008">
   <tags>
     <tag type="tok">for</tag>
     <tag type="cat">(n\n)/np</tag>
     <tag type="sym">for</tag>
     <tag type="lemma">for</tag>
     <tag type="from">32</tag>
     <tag type="to">35</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Beneficiary]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1009">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">the</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">the</tag>
     <tag type="lemma">the</tag>
     <tag type="from">36</tag>
     <tag type="to">39</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DEF</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1010">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">date</tag>
     <tag type="cat">n</tag>
     <tag type="sym">time</tag>
     <tag type="lemma">time</tag>
     <tag type="from">40</tag>
     <tag type="to">44</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1011">
   <tags>
     <tag type="tok">in</tag>
     <tag type="cat">((s:ng\np)\(s:ng\np))/np</tag>
     <tag type="sym">in</tag>
     <tag type="lemma">in</tag>
     <tag type="from">45</tag>
     <tag type="to">47</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Location]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1012">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">the</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">the</tag>
     <tag type="lemma">the</tag>
     <tag type="from">48</tag>
     <tag type="to">51</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">DEF</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1013">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">evening</tag>
     <tag type="cat">n</tag>
     <tag type="sym">evening</tag>
     <tag type="lemma">evening</tag>
     <tag type="from">52</tag>
     <tag type="to">59</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1014">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">.</tag>
     <tag type="cat">s:dcl\s:dcl</tag>
     <tag type="sym">.</tag>
     <tag type="lemma">.</tag>
     <tag type="from">59</tag>
     <tag type="to">60</tag>
     <tag type="pos">.</tag>
     <tag type="sem">NIL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b2">
  <domain>
   <dr label="b1" name="x1" from="0" to="-1"></dr>
   <dr label="b2" name="e1" from="10" to="17"></dr>
   <dr label="b2" name="x2" from="23" to="-1"></dr>
   <dr label="b2" name="t1" from="0" to="0"></dr>
   <dr label="b3" name="x3" from="48" to="51"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="x1" symbol="person" synset="person.n.01" from="0" to="5"></pred>
   </cond>
   <cond label="b1">
    <named arg="x1" symbol="frank" from="0" to="5"></named>
   </cond>
   <cond label="b2">
    <pred arg="t1" symbol="time" synset="time.n.01" from="40" to="44"></pred>
   </cond>
   <cond label="b2">
    <comp symbol="TPR" arg1="t1" arg2="now" from="6" to="9"></comp>
   </cond>
   <cond label="b2">
    <pred arg="t1" symbol="time" synset="time.n.08" from="6" to="9"></pred>
   </cond>
   <cond label="b2">
    <pred arg="e1" symbol="wait" synset="wait.v.01" from="10" to="17"></pred>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="t1" symbol="Time" framenet="Time" from="6" to="9"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x3" symbol="Location" framenet="Containing@Container" from="45" to="47"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x2" symbol="Theme" framenet="Activity_start@Activity" from="18" to="22"></rel>
   </cond>
   <cond label="b2">
    <rel arg1="e1" arg2="x1" symbol="Location" framenet="Process_continue@Place" from="10" to="17"></rel>
   </cond>
   <cond label="b2">
    <pred arg="x2" symbol="pleasure" synset="pleasure.n.01" from="23" to="31"></pred>
   </cond>
   <cond label="b2">
    <rel arg1="x2" arg2="t1" symbol="Beneficiary" framenet="Beneficiary" from="32" to="35"></rel>
   </cond>
   <cond label="b3">
    <pred arg="x3" symbol="evening" synset="evening.n.01" from="52" to="59"></pred>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>

=== Bhavesh-github-zen/Word_Phrase_Alignment_-B-/PMB/pmb-sample-4.0.0/data/en/bronze/p00/d0077/en.drs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdrs-output SYSTEM "src/dtd/xdrs.dtd">
<xdrs-output version="'boxer v1.00 (unix build on 21 May 2021, 16:29:40)'">
<!-- What ø Tom said does n't apply in this situation . --> 

<xdrs xml:id="xdrs1">
 <taggedtokens>
  <tagtoken xml:id="i1001">
   <tags>
     <tag type="tok">What</tag>
     <tag type="cat">np/(s:dcl/np)</tag>
     <tag type="sym">entity</tag>
     <tag type="lemma">entity</tag>
     <tag type="from">0</tag>
     <tag type="to">4</tag>
     <tag type="pos">WP</tag>
     <tag type="sem">QUE</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Equal]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1002">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">ø</tag>
     <tag type="cat">np/n</tag>
     <tag type="wordnet">O</tag>
     <tag type="sense">0</tag>
     <tag type="sym">ø</tag>
     <tag type="lemma">ø</tag>
     <tag type="sem">DEF</tag>
     <tag type="from">5</tag>
     <tag type="to">-1</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1003">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">Tom</tag>
     <tag type="cat">n</tag>
     <tag type="sym">tom</tag>
     <tag type="lemma">tom</tag>
     <tag type="from">5</tag>
     <tag type="to">8</tag>
     <tag type="pos">NNP</tag>
     <tag type="sem">PER</tag>
     <tag type="wordnet">male.n.02</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1004">
   <tags>
     <tag type="tok">said</tag>
     <tag type="cat">((s:dcl\np)/np)/(s:dcl\np)</tag>
     <tag type="sym">say</tag>
     <tag type="lemma">say</tag>
     <tag type="from">9</tag>
     <tag type="to">13</tag>
     <tag type="pos">VBD</tag>
     <tag type="sem">EPS</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="2">[Topic,Agent]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1005">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">does</tag>
     <tag type="cat">(s:dcl\np)/(s:b\np)</tag>
     <tag type="sym">do</tag>
     <tag type="lemma">do</tag>
     <tag type="from">14</tag>
     <tag type="to">18</tag>
     <tag type="pos">VBZ</tag>
     <tag type="sem">NOW</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1006">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">n't</tag>
     <tag type="cat">(s:dcl\np)\(s:dcl\np)</tag>
     <tag type="sym">not</tag>
     <tag type="lemma">not</tag>
     <tag type="from">18</tag>
     <tag type="to">21</tag>
     <tag type="pos">RB</tag>
     <tag type="sem">NOT</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1007">
   <tags>
     <tag type="tok">apply</tag>
     <tag type="cat">(s:b\np)/pp</tag>
     <tag type="sym">apply</tag>
     <tag type="lemma">apply</tag>
     <tag type="from">22</tag>
     <tag type="to">27</tag>
     <tag type="pos">VB</tag>
     <tag type="sem">EXS</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Agent]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1008">
   <tags>
     <tag type="tok">in</tag>
     <tag type="cat">pp/np</tag>
     <tag type="sym">in</tag>
     <tag type="lemma">in</tag>
     <tag type="from">28</tag>
     <tag type="to">30</tag>
     <tag type="pos">IN</tag>
     <tag type="sem">REL</tag>
     <tag type="wordnet">O</tag>
     <tag type="verbnet" n="1">[Location]</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1009">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">this</tag>
     <tag type="cat">np/n</tag>
     <tag type="sym">this</tag>
     <tag type="lemma">this</tag>
     <tag type="from">31</tag>
     <tag type="to">35</tag>
     <tag type="pos">DT</tag>
     <tag type="sem">PRX</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1010">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">situation</tag>
     <tag type="cat">n</tag>
     <tag type="sym">situation</tag>
     <tag type="lemma">situation</tag>
     <tag type="from">36</tag>
     <tag type="to">45</tag>
     <tag type="pos">NN</tag>
     <tag type="sem">CON</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
  <tagtoken xml:id="i1011">
   <tags>
     <tag type="verbnet" n="0">[]</tag>
     <tag type="tok">.</tag>
     <tag type="cat">np\np</tag>
     <tag type="sym">.</tag>
     <tag type="lemma">.</tag>
     <tag type="from">45</tag>
     <tag type="to">46</tag>
     <tag type="pos">.</tag>
     <tag type="sem">NIL</tag>
     <tag type="wordnet">O</tag>
   </tags>
  </tagtoken>
 </taggedtokens>
 <drs label="b1">
  <domain>
   <dr label="b1" name="x1" from="0" to="4"></dr>
   <dr label="b2" name="x2" from="5" to="-1"></dr>
   <dr label="b1" name="e1" from="9" to="13"></dr>
   <dr label="b1" name="t1" from="9" to="13"></dr>
   <dr label="b1" name="e2" from="0" to="0"></dr>
  </domain>
  <conds>
   <cond label="b1">
    <pred arg="x1" symbol="entity" synset="entity.n.01" from="0" to="4"></pred>
   </cond>
   <cond label="b2">
    <pred arg="x2" symbol="male" synset="male.n.02" from="5" to="8"></pred>
   </cond>
   <cond label="b2">
    <named arg="x2" symbol="tom" from="5" to="8"></named>
   </cond>
   <cond label="b1">
    <pred arg="t1" symbol="time" synset="time.n.08" from="9" to="13"></pred>
   </cond>
   <cond label="b1">
    <comp symbol="TPR" arg1="t1" arg2="now" from="9" to="13"></comp>
   </cond>
   <cond label="b1">
    <pred arg="e1" symbol="say" synset="say.v.01" from="9" to="13"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="t1" symbol="Time" framenet="Time" from="9" to="13"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x2" symbol="Agent" framenet="Agent" from="9" to="13"></rel>
   </cond>
   <cond label="b1">
    <rel arg1="e1" arg2="x1" symbol="Theme" framenet="Theme" from="9" to="13"></rel>
   </cond>
   <cond label="b1">
    <not from="18" to="21">
     <drs label="b3">
      <domain>
       <dr label="b3" name="e3" from="22" to="27"></dr>
       <dr label="b4" name="x3" from="31" to="35"></dr>
       <dr label="b1" name="t2" from="14" to="18"></dr>
      </domain>
      <conds>
       <cond label="b3">
        <rel arg1="e1" arg2="e3" symbol="Recipient" framenet="Recipient" from="9" to="13"></rel>
       </cond>
       <cond label="b1">
        <pred arg="t2" symbol="time" synset="time.n.08" from="14" to="18"></pred>
       </cond>
       <cond label="b1">
        <comp symbol="EQU" arg1="t2" arg2="now" from="14" to="18"></comp>
       </cond>
       <cond label="b3">
        <pred arg="e3" symbol="apply" synset="apply.v.01" from="22" to="27"></pred>
       </cond>
       <cond label="b3">
        <rel arg1="e3" arg2="t2" symbol="Time" framenet="Time" from="14" to="18"></rel>
       </cond>
       <cond label="b3">
        <rel arg1="e3" arg2="x3" symbol="Location" framenet="Containing@Container" from="28" to="30"></rel>
       </cond>
       <cond label="b3">
        <rel arg1="e3" arg2="x1" symbol="Agent" framenet="Placing@Agent" from="22" to="27"></rel>
       </cond>
       <cond label="b4">
        <pred arg="x3" symbol="situation" synset="situation.n.01" from="36" to="45"></pred>
       </cond>
      </conds>
     </drs>
    </not>
   </cond>
   <cond label="b1">
    <pred arg="e2" symbol="event" synset="event.v.01" from="0" to="0"></pred>
   </cond>
   <cond label="b1">
    <rel arg1="e2" arg2="x1" symbol="Participant" framenet="Participant" from="0" to="0"></rel>
   </cond>
  </conds>
 </drs>
</xdrs>
</xdrs-output>
